# COPIANDO IMAGEM OFICIAL DO POSTGRES
FROM postgres:latest

# CARREGANDO VARIAVEIS DE AMBIENTE DE LOGIN, SENHA E NOME DO BANCO.

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=db

# EXPONDO A PORTA 9000 PARA CONEXÕES EXTERNAS.

EXPOSE 5432